In [60]:
import numpy as np
import csv

data = []
labels = []

with open('sample_train.csv','r') as f:
    rows = csv.reader(f)
    for row in rows:
        data.append(row[1:])
        labels.append(row[0])
data = np.matrix(data).astype(np.float)
data_mean = np.mean(data,axis=0)
data_cov = np.linalg.inv(np.cov(data))
data = data - data_mean
data = np.dot(data_cov,data) 
labels = np.array(labels).astype(np.float)

In [61]:
its = 0

def sigmoid_activation(w,n=1.5,gamma = 10):
    print(w)
    
    global its
    
    its += 1
    if(its>100):
        return w
    
    y = []
    for i in range(len(labels)):
        y.append((labels[i]+1)/2)
    
    z = gamma * np.matmul(data,w)
    
    h = (np.exp(-z)))
    y_10 = np.empty((6000,10))
    for i in range(10):
        y_10[:,i]=y
    gradient = np.matmul(np.transpose(data),h-y_10) / len(data)
    w = w - n * gradient
    return sigmoid_activation(w)

In [62]:
w = sigmoid_activation(np.random.rand(784,10))

[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 0.72768844 0.87272968 0.62368256]
 [0.6574194  0.1653783  0.19539582 ... 0.04217399 0.85056128 0.076814  ]
 ...
 [0.97140161 0.83461665 0.52396032 ... 0.01979779 0.61380235 0.39279078]
 [0.67139996 0.04066242 0.4506439  ... 0.80297934 0.8442679  0.62199701]
 [0.28701365 0.2257281  0.7359739  ... 0.86442862 0.58471541 0.60352719]]
[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 0.72768844 0.87272968 0.62368256]
 [0.6574194  0.1653783  0.19539582 ... 0.04217399 0.85056128 0.076814  ]
 ...
 [0.97140161 0.83461665 0.52396032 ... 0.01979779 0.61380235 0.39279078]
 [0.67139996 0.04066242 0.4506439  ... 0.80297934 0.8442679  0.62199701]
 [0.28701365 0.2257281  0.7359739  ... 0.86442862 0.58471541 0.60352719]]
[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 

[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 0.72768844 0.87272968 0.62368256]
 [0.6574194  0.1653783  0.19539582 ... 0.04217399 0.85056128 0.076814  ]
 ...
 [0.97140161 0.83461665 0.52396032 ... 0.01979779 0.61380235 0.39279078]
 [0.67139996 0.04066242 0.4506439  ... 0.80297934 0.8442679  0.62199701]
 [0.28701365 0.2257281  0.7359739  ... 0.86442862 0.58471541 0.60352719]]
[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 0.72768844 0.87272968 0.62368256]
 [0.6574194  0.1653783  0.19539582 ... 0.04217399 0.85056128 0.076814  ]
 ...
 [0.97140161 0.83461665 0.52396032 ... 0.01979779 0.61380235 0.39279078]
 [0.67139996 0.04066242 0.4506439  ... 0.80297934 0.8442679  0.62199701]
 [0.28701365 0.2257281  0.7359739  ... 0.86442862 0.58471541 0.60352719]]
[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 

[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 0.72768844 0.87272968 0.62368256]
 [0.6574194  0.1653783  0.19539582 ... 0.04217399 0.85056128 0.076814  ]
 ...
 [0.97140161 0.83461665 0.52396032 ... 0.01979779 0.61380235 0.39279078]
 [0.67139996 0.04066242 0.4506439  ... 0.80297934 0.8442679  0.62199701]
 [0.28701365 0.2257281  0.7359739  ... 0.86442862 0.58471541 0.60352719]]
[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 0.72768844 0.87272968 0.62368256]
 [0.6574194  0.1653783  0.19539582 ... 0.04217399 0.85056128 0.076814  ]
 ...
 [0.97140161 0.83461665 0.52396032 ... 0.01979779 0.61380235 0.39279078]
 [0.67139996 0.04066242 0.4506439  ... 0.80297934 0.8442679  0.62199701]
 [0.28701365 0.2257281  0.7359739  ... 0.86442862 0.58471541 0.60352719]]
[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 

[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 0.72768844 0.87272968 0.62368256]
 [0.6574194  0.1653783  0.19539582 ... 0.04217399 0.85056128 0.076814  ]
 ...
 [0.97140161 0.83461665 0.52396032 ... 0.01979779 0.61380235 0.39279078]
 [0.67139996 0.04066242 0.4506439  ... 0.80297934 0.8442679  0.62199701]
 [0.28701365 0.2257281  0.7359739  ... 0.86442862 0.58471541 0.60352719]]
[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 0.72768844 0.87272968 0.62368256]
 [0.6574194  0.1653783  0.19539582 ... 0.04217399 0.85056128 0.076814  ]
 ...
 [0.97140161 0.83461665 0.52396032 ... 0.01979779 0.61380235 0.39279078]
 [0.67139996 0.04066242 0.4506439  ... 0.80297934 0.8442679  0.62199701]
 [0.28701365 0.2257281  0.7359739  ... 0.86442862 0.58471541 0.60352719]]
[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 

[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 0.72768844 0.87272968 0.62368256]
 [0.6574194  0.1653783  0.19539582 ... 0.04217399 0.85056128 0.076814  ]
 ...
 [0.97140161 0.83461665 0.52396032 ... 0.01979779 0.61380235 0.39279078]
 [0.67139996 0.04066242 0.4506439  ... 0.80297934 0.8442679  0.62199701]
 [0.28701365 0.2257281  0.7359739  ... 0.86442862 0.58471541 0.60352719]]
[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 0.72768844 0.87272968 0.62368256]
 [0.6574194  0.1653783  0.19539582 ... 0.04217399 0.85056128 0.076814  ]
 ...
 [0.97140161 0.83461665 0.52396032 ... 0.01979779 0.61380235 0.39279078]
 [0.67139996 0.04066242 0.4506439  ... 0.80297934 0.8442679  0.62199701]
 [0.28701365 0.2257281  0.7359739  ... 0.86442862 0.58471541 0.60352719]]
[[0.04449973 0.56929894 0.42356762 ... 0.29709279 0.17662503 0.32261539]
 [0.76218993 0.54030222 0.84826738 ... 

In [63]:
# acc = 0
print(np.matmul(data,w))

# for i in range(len(labels)):
#     print(preds[i,0],labels[i])
#     if preds[i,0]/10**8 == labels[i]:
#         acc += 1

[[-1.13155971e+26 -1.13155971e+26 -1.13155971e+26 ... -1.13155971e+26
  -1.13160032e+26 -1.13155971e+26]
 [ 2.68116679e+26  2.68116679e+26  2.68116679e+26 ...  2.68116679e+26
   2.68126475e+26  2.68116679e+26]
 [-1.57925850e+26 -1.57925850e+26 -1.57925850e+26 ... -1.57925850e+26
  -1.57931640e+26 -1.57925850e+26]
 ...
 [ 5.56384157e+25  5.56384157e+25  5.56384157e+25 ...  5.56384157e+25
   5.56404591e+25  5.56384157e+25]
 [ 2.54951601e+26  2.54951601e+26  2.54951601e+26 ...  2.54951601e+26
   2.54960965e+26  2.54951601e+26]
 [ 8.65257191e+25  8.65257191e+25  8.65257191e+25 ...  8.65257191e+25
   8.65288968e+25  8.65257191e+25]]


In [50]:
print(acc)

0
